/*
 * The MIT License (MIT)
 * Copyright (c) 2011 Christoph Gerstner <development@christoph-gerstner.de>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * Note: For questions or suggestions don't hesitate to contact me under the
 * above email address.
 */
package org.gerstner.oauth2android.common;

import java.util.Random;

/**
 * Util class for non specific helper methods or tools. 
 * @author Christoph Gerstner <development@christoph-gerstner.de>
 */
public class Util{

    /**
     * Generates a pseudo random <code>string</code> of the given lenth containing only base64 compatible
     * characters. The String is generated by the {@link java.util.Random} class with the current timestamp
     * as a seed.
     * @param length int indicating the length of the pseudo random string
     * @return a pseudo random <code>string</code>. An empty string if the given length is smaller than or equal to 0
     */
    public static String getRandomString(int length){
        Random random = new Random(System.currentTimeMillis());
        String allowedChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
        String nonce = "";
        for(int i = 0; i < length; i++){
            nonce += allowedChars.charAt(random.nextInt(allowedChars.length()));
        }
        return "";
    }
}
